### ISSUE TITLE
Insufficient version for Getopt::Long::Descriptive

### ISSUE THREAD

**Issue by barefootcoder** [arodland/CLI-Osprey#23]
Since you're using `prereqs = cpanfile` in your `dist.ini`, and since your `cpanfile` doesn't specify a version for `Getopt::Long::Descriptive`, you don't get a minimum version in your `META.json`.  But line 10 of `lib/CLI/Osprey/Descriptive.pm` specifies:
```
use Getopt::Long::Descriptive 0.100;
```
As you might imagine, this causes errors in upstream distros (e.g. [this failure report from CPAN Testers](http://www.cpantesters.org/cpan/report/a18be2f2-4bd9-11ea-94e7-0c571f24ea8f) for my module [Pb](https://metacpan.org/pod/Pb)).

I can confirm that just removing the `prereqs` line in your `dist.ini` fixes it, but maybe you prefer to update your `cpanfile` instead—I'm not sure what your goal in using `cpanfile` was anyway, so I don't want to second-guess you.  But it would be helpful if you could fix this, and it's a trivial fix either way.

Thx so much!  As you probably noticed if you took a look at my upstream module, `CLI::Osprey` is a **huge** building block for `Pb`, so I'm really glad you wrote it.

**Comment by arodland** [comment]
Thank you. I'll fix up the prereq. I'm actually quite surprised, I thought that no one was using this!

**Comment by barefootcoder** [comment]
> I'm actually quite surprised, I thought that no one was using this!

Actually, I stumbled on it by accident, but it's easily the best of the `App::Cmd` modules, and I've tried quite a few of them. ;->  This made my life writing Leadpipe _much_ happier. :-)

BTW, the next problem I'm going to run into is [RT/125793](https://rt.cpan.org/Public/Bug/Display.html?id=125793).  Do you want me to make a GitHub issue for that here, or just continue the discussion on RT?

**Comment by arodland** [comment]
BTW the reason for using Prereqs::FromCPANFile instead of AutoPrereqs is to force me to keep the CPANFile up-to-date to ensure that people can easily do development without having dzil. Perhaps I should write a CPANFile generator *from* the dzil-gathered prereqs (or perhaps someone has while I wasn't looking), but in the meantime I'll update the CPANFile.

Thanks.

**Comment by arodland** [comment]
RT#125793 was fixed by #10, which didn't make it into a release. I'll cut a release and close that.
